name: amap_search_fluttify
description: An `Amap` search component, based on `fluttify` engine.
version: 0.2.11+d2eb645
author: yohom <382146139@qq.com>
homepage: https://github.com/fluttify-project/amap_search_fluttify

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  foundation_fluttify: ^0.0.9
  amap_core_fluttify: ^0.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: me.yohom.amap_search_fluttify
    pluginClass: AmapSearchFluttifyPlugin