name: amap_search_fluttify
description: A `Amap` search component, based on `fluttify` engine.
version: 0.0.5
author: yohom <382146139@qq.com>
homepage: https://github.com/yohom/amap_search_fluttify

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: me.yohom.amap_search_fluttify
    pluginClass: AmapSearchFluttifyPlugin